import Link from "next/link";
import styles from "./main-header.module.css";
import Head from "next/head";

export default function MainHeader() {
  return (
    <div>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header className={styles.header}>
        <div className={styles.logo}>
          <Link href="/">Next Events</Link>
        </div>

        <nav className={styles.navigation}>
          {/* <ul>
          <li> */}
          <Link href="/events">Browse All Events</Link>
          {/* </li>
        </ul> */}
        </nav>
      </header>
    </div>
  );
}
