import { getFeaturedEvents } from "../dummy-data";
import Head from "next/head";
import EventList from "../components/events/EventList";

export default function HomePage() {
  const featuredEvents = getFeaturedEvents();

  return (
    <div>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div>
        <EventList items={featuredEvents} />
      </div>
    </div>
  );
}
